version: 0.0
os: linux
files:
        - source: /
          destination: /home/ubuntu/codepipeline/reactjs/

hooks:
        BeforeInstall:
                - location: Scripts/install_dependencies.sh
                - location: Scripts/BeforeInstall.sh
                  timeout: 300
                  runas: root
        AfterInstall:
                - location: Scripts/startApplication.sh
                  timeout: 600
                  runas: root

